---
title: "article_4: Prenatal HIV exposure linked to decreased infant immunity"
description: |
  A short description of the post.
author:
  - name: claude foko
    url: (https://github.com/BioDataScience-Course/sdd1-19m-belgium-claude.git)
date: 12-03-2019
output:
  distill::distill_article:
    self_contained: false
---

## vocabulary 


|word from the text | Synonym/explanation in English |
|-------------------|--------------------------------|
|   increased       |    grow                        |
|   morbidity       |     sickly                     |
|    childhood      |  the state or period of babyhood                              |
|                   |                                |

## Analysis table 

|                                |                                                               |
|--------------------------------|---------------------------------------------------------------|
| Researchers                    | scientists at the University of Rhode Island                  |
| Published in?                  |    September 10, 2019                                        |
| general topic                  |   demonstrate the concrete evidence linking the specific immune responses of HIV-negative babies to their mothers' HIV status.                                                          |
| Procedure/what was examined?   |    To arrive at their conclusions, researchers compared the T-cell receptor beta-chain repertoire of cord blood samples from HIV-exposed uninfected infants to samples collected from mother-child pairs unaffected by HIV, but who were living in the same communities.                                                          |
|  Conclusions/discovery?        |  The analysis revealed two clusters of HIV-exposed but uninfected babies: one cluster born similar to healthy infants without HIV exposure while the other cluster born with a significantly reduced immune repertoire.                                                             |
|  Remaining questions?          |   what would be the contribution of this study on the prevention or reduction of the mortality rate of infants carrying hiv ?                                                           |
(https://www.sciencedaily.com/releases/2019/09/190910134326.htm)

```


