---
title: "article 2:Long-acting injectable multi-drug implant shows promise for HIV prevention and treatment"
description: |

author:
  - name: claude foko
    url: (https://github.com/BioDataScience-Course/sdd1-19m-belgium-claude.git)
date: 05-03-2020
output:
  distill::distill_article:
    self_contained: false
---
## vocabulary 

|word from the text | Synonym/explanation in English |
|-------------------|--------------------------------|
| burden            |           charge              |
| counteract        |  prevent                       |
| adherence         |  sticking to                              |

## Analysis table 

|                                |                                                               |
|--------------------------------|---------------------------------------------------------------|
| Researchers                    | "J. Victor Garcia", PhD, professor of medicine at UNC School of Medicine, director of the International Center for the Advancement of Translational Science and member of the UNC Center for AIDS Research. and "Rahima Benhabbour", PhD, MSc, first author of the study and assistant professor in the UNC_NCSU Joint Department of Biomedical Engineering.                                                          |
| Published in?                  |  September 20, 2019                                                 |
| general topic                  |  the development of an HIV vaccine that would be more effective than retroviral                                                             |
| Procedure/what was examined?   | the authors realized an injectable implant that is composed of three elements: an organic solvent, a polymer and the drug (s) to be administered. The formulation gives a honey-like liquid that turns into a solid when injected under the skin. This phase reversal occurs when the solvent diffuses into the body, leaving behind the polymer and the drug (s) - their combination determines the time during which the drug will be released into the bloodstream.                                                              |
|  Conclusions/discovery?        | In conclusion, the injectable drug implant created by the UNC research team is the first to address several of the disadvantages of the current method of administering long-acting drugs against HIV, namely the ability to remove it and to quickly eliminate the presence of residual drug (s) in the system.                                                              |
|  Remaining questions?          | At the end of this article, the question that plagues me is whether this implant does not have any problem because it is not mentioned anywhere in the research.                                                              |
 "science daily: https://www.sciencedaily.com/releases/2019/09/190920124650.htm"



