---
title: "article_4: Prenatal HIV exposure linked to decreased infant immunity"
description: |
  
author:
  - name: claude foko
  
date: 17-09-2019
output:
  distill::distill_article:
    self_contained: false
---
## vocabulary 

|word from the text | Synonym/explanation in English |
|-------------------|--------------------------------|
|                   |                         |
|                   |                         |
|                   |                          |

## Analysis table 

|                                |                                                               |
|--------------------------------|---------------------------------------------------------------|
| Researchers                    |  scientists at the University of Rhode Island                                    |
| Published in?                  |  September 10, 2019                                         |
| general topic                  |  we are dealing here with the demonstration by concrete evidence linking the specific immune responses of HIV-negative babies to their mothers' HIV-positive status.                                                            |
| Procedure/what was examined?   |  To arrive at their conclusions, researchers compared the T-cell receptor beta-chain repertoire of cord blood samples from HIV-exposed uninfected infants to samples collected from mother-child pairs unaffected by HIV, but who were living in the same communities.                                                            |
|  Conclusions/discovery?        |  The analysis revealed two clusters of HIV-exposed but uninfected babies: one cluster born similar to healthy infants without HIV exposure while the other cluster born with a significantly reduced immune repertoire.The reduced immune repertoire in HIV-exposed but uninfected infants found in the study may help explain the increased risk of morbidity in this population and emphasizes the need for special care and attention to this group.|

```
